### ISSUE TITLE
Classify cute animals

### ISSUE THREAD

**Issue by ekinbukulmez** [ekinbukulmez/CITS3200-Project#20]
**Description**
Establish backend endpoint that classifies images into blank images and animals.

**Definition of done**
- Function able to classify images given image URLs into blank or animals using the images' metadata & Vision API

**Tasks**
- [x] Establish backend endpoint.
- [x] Classify animal pics.
- [x] Classify blank pics.
- [ ] Tests
- [ ] Documentation
