### ISSUE TITLE
Animal image classification endpoint for a single image

### ISSUE THREAD

**Issue by Pixeladed** [ekinbukulmez/CITS3200-Project#3]
**Description**
Create an HTTP endpoint that receives an image link and a GCP key (JSON object) as input and respond with whether or not that image is a photo of an animal.

**Definition of done**
- Compiles without errors
- Able to access the endpoint through `localhost:{port}/{path}`
- Endpoint receives an image URL either through params, body or query string
- Responds with status `400` if no image URL was given
- Otherwise, responds with status `200` and a JSON object indicating whether the image is of an animal
- Documentation on how the endpoint works
- Documentation on how to use the endpoint
- Accept GCP key as input

**Tasks**
- [ ] Implement HTTP server
- [ ] implement GCP key parsing
- [ ] implement image metadata parsing
- [ ] implement GCP Vision API call
- [ ] implement endpoint routers and handlers
- [ ] documentation
- [ ] tests
