### ISSUE TITLE
Interface homepage

### ISSUE THREAD

**Issue by Pixeladed** [ekinbukulmez/CITS3200-Project#5]
**Description**
A simple web page that displays the title of the module, a short description

**Definition of done**
- Instructions on how to view the page
- Able to view the page on desktops without errors
- Include a sensible title and description of the module

**Tasks**
- [ ] Create a title and a description
- [ ] Implement home page
- [ ] Document how to view the page
