### ISSUE TITLE
File uploading form

### ISSUE THREAD

**Issue by Pixeladed** [ekinbukulmez/CITS3200-Project#7]
**Description**
Modify the page created in #5 to include a form such that users can 
1. Select and upload their GCP key
2. Select and upload multiple images

**Definition of done**
- A form is present on the page with no errors
- User can select a file on their system to upload as a key
- User can only select a `.json` file as the key
- User can select multiple images on their system to upload as images
- User can only upload images that are [supported by GCP Cloud Vision API](https://cloud.google.com/vision/docs/supported-files)

**Tasks**
- [ ] Implement key file input
- [ ] Implement images file input
- [ ] Implement key file type restriction
- [ ] Implement images file type restriction
- [ ] Docmentation
- [ ] Tests
