### ISSUE TITLE
Connect interface to endpoint

### ISSUE THREAD

**Issue by Pixeladed** [ekinbukulmez/CITS3200-Project#8]
**Description**
Connect the form created in #7 to the endpoint created in #4 and display the result of the task to the user. Images are classified one by one and the result is immediately displayed to the user.

**Definition of done**
- Use the image classification endpoint to process selected images
- Display processed images in their respective classification
- Process all images selected by the user
- Process each image individually
- If the endpoint fails, put the image back in the queue to try again

**Tasks**
- [ ] Process image uploaded using the endpoint
- [ ] Display processed images in different groups
- [ ] Display pending images to be processed
- [ ] Documentation
- [ ] Test
